const InfoFile = [
  {
    id: 1,
    value: 0,
    name: "hello this is a test",
    price: 65.0,
    customizable: "customizable",
    description:
      "Panko breaded Mac and Cheese balls fried until golden brown and served with our homemade marinara sause",
    image: null,
    color: "Soup",
    veg: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Non_veg_symbol.svg",
    seller: "Best Seller",
    recommended: "recommended",
  },
  {
    id: 2,
    value: 0,
    name: "Stuffed Cherry Peppers",
    price: 79.0,
    customizable: "",
    description:
      "Panko breaded Mac and Cheese balls fried until golden brown and served with our homemade marinara sause ",
    image: "https://scx2.b-cdn.net/gfx/news/hires/2016/howcuttingdo.jpg",
    color: "Appetizer",
    veg: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Non_veg_symbol.svg",
    seller: "",
    recommended: "recommended",
  },
  {
    id: 3,
    value: 0,
    name: "Broiled Brie with Canberry Chutney",
    price: 27.0,
    customizable: "customizable",
    description:
      "Panko breaded Mac and Cheese balls fried until golden brown and served with our homemade marinara sause",
    image: "https://scx2.b-cdn.net/gfx/news/hires/2016/howcuttingdo.jpg",
    color: "Recommended",
    veg: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Non_veg_symbol.svg",
    seller: "Best Seller",
    recommended: "recommended",
  },
  {
    id: 4,
    value: 0,
    name: "Canapes and Crostini",
    price: 27.0,
    customizable: "customizable",
    description:
      "Panko breaded Mac and Cheese balls fried until golden brown and served with our homemade marinara sause",
    image: null,
    color: "Soup",
    veg: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Non_veg_symbol.svg",
    seller: "Best Seller",
    recommended: "recommended",
  },
  {
    id: 5,
    value: 0,
    name: "hello this is a test",
    price: 65.0,
    customizable: "customizable",
    description:
      "Panko breaded Mac and Cheese balls fried until golden brown and served with our homemade marinara sause",
    image: null,
    color: "Soup",
    veg: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Non_veg_symbol.svg",
    seller: "Best Seller",
    recommended: "recommended",
  },
  {
    id: 6,
    value: 0,
    name: "Stuffed Cherry Peppers",
    price: 79.0,
    customizable: "",
    description:
      "Panko breaded Mac and Cheese balls fried until golden brown and served with our homemade marinara sause ",
    image: "https://scx2.b-cdn.net/gfx/news/hires/2016/howcuttingdo.jpg",
    color: "Appetizer",
    veg: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Non_veg_symbol.svg",
    seller: "",
    recommended: "recommended",
  },
  {
    id: 7,
    value: 0,
    name: "Broiled Brie with Canberry Chutney",
    price: 27.0,
    customizable: "customizable",
    description:
      "Panko breaded Mac and Cheese balls fried until golden brown and served with our homemade marinara sause",
    image: "https://scx2.b-cdn.net/gfx/news/hires/2016/howcuttingdo.jpg",
    color: "Recommended",
    veg: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Non_veg_symbol.svg",
    seller: "Best Seller",
    recommended: "recommended",
  },
  {
    id: 8,
    value: 0,
    name: "Canapes and Crostini",
    price: 27.0,
    customizable: "customizable",
    description:
      "Panko breaded Mac and Cheese balls fried until golden brown and served with our homemade marinara sause",
    image: null,
    color: "Soup",
    veg: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Non_veg_symbol.svg",
    seller: "Best Seller",
    recommended: "recommended",
  },
];

export default InfoFile;
